### ISSUE TITLE
Insufficient permissions for maniaexchange

### ISSUE THREAD

**Issue by fily-gif** [GreepTheSheep/openplanet-maniaexchange-menu#15]
As I said in the tittle, I get the error "Insufficient permissions for "maniaexchange"", I have no idea why or how this is happening, but it is the only error that says something about this plugin, I have tried reinstalling it and installing optional plugins (better chat, itemexchange), and it did not help, it's my first time using openplanet and maniaexchange.
![image](https://user-images.githubusercontent.com/73085550/216880074-e1c739c0-bfb2-4429-9da7-63e4b3b4568d.png)

**Comment by GreepTheSheep** [comment]
You need to run Standard edition of the game since it allows to play custom maps

**Comment by fily-gif** [comment]
> You need to run at least Standard edition of the game since it allows to play custom maps

ohhhh, okay thanks!
