### ISSUE TITLE
Add a Titlepack filter

### ISSUE THREAD

**Issue by AurelSM** [GreepTheSheep/openplanet-maniaexchange-menu#20]
Would be nice to have a TitlePack filter / or gamemode .
Something more accurated when we search maps.

I'm on Maniaplanet 4 / Shootmania.

Thanks, and great plugin again :)

**Comment by GreepTheSheep** [comment]
Titlepack filtering cannot be possible due to ManiaExchange API, but you can filter with Environments.
Sadly Shootmania has only one Environment: Storm.
I added recently TitlePack name on map info.

I, anyway, added enviro filtering.
