### ISSUE TITLE
Tab for "play later" and "favorites" alongside other tabs in the TMX UI (suggestion)

### ISSUE THREAD

**Issue by oMqngo** [GreepTheSheep/openplanet-maniaexchange-menu#22]
Hello,

I have a small suggestion regarding the tabs in the TMX UI. Would it be possible to add 1 tab containing "play later" and "favorites" (or 2 individual tabs is fine too), which act the same as browsing maps in for example the "featured" tab where you can hover over the title and see a little preview of the map or the details of it when you press on the "i" icon.

Reason im suggesting this is because I find myself always searching up the individual maps to be able to see the info about them, which you cant do in the small TMX menu in the top bar of the OpenPlanet UI...

**Comment by GreepTheSheep** [comment]
Tab created, will look like this

![image](https://github.com/user-attachments/assets/3af70b54-ac35-464a-8631-9579e87d10ee)
