### ISSUE TITLE
Play later - Error parsing infos

### ISSUE THREAD

**Issue by Protoster** [GreepTheSheep/openplanet-maniaexchange-menu#23]
When there are maps in the "play later" list, a warning notification is displayed every time you launch the game (or load the plugin) for each item in the list.
See screenshot:
![image](https://github.com/GreepTheSheep/openplanet-maniaexchange-menu/assets/5383872/1a88cb8c-b5e7-41ce-b4b2-9a87d152d834)
However, it does not appear to result in any broken functionality. I can still add/remove items from the "play later" list, view info, or play the map.

**Comment by Fort-TM** [comment]
This happens because the JSON saved was missing some values, so when it tries to load the map info, it accesses a non-existing key, which throws an error. Fixed by #29
